name: 同步 python 公共仓库

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: 检出代码
        uses: actions/checkout@v2

      - name: 克隆公共仓库
        run: git clone https://github.com/WYN-GraduationProject/WYN-GraduationProject-common.git

      - name: 复制文件
        run: |
          cd WYN-GraduationProject-common
          git checkout main
          source .env
          cp -a -r -f ./proto/ ${_321CQU_PUBLIC_REPOSITORY_PATH}/micro_services_protobuf/
          cp -a -r -f ./python_package/_321CQU/ ${_321CQU_PUBLIC_REPOSITORY_PATH}/python_package/
          cp -a -r -f ./python_package/micro_services_protobuf/ ${_321CQU_PUBLIC_REPOSITORY_PATH}/python_package/
          cp -a -r -f ./proto_build/python/micro_services_protobuf ${_321CQU_PUBLIC_REPOSITORY_PATH}/python_package/
          cp -a -r -f ./docker-compose.yml ${_321CQU_PUBLIC_REPOSITORY_PATH}/
          cp -a -r -f .env ${_321CQU_PUBLIC_REPOSITORY_PATH}/
        env:
          _321CQU_PUBLIC_REPOSITORY_PATH: ${{ secrets._321CQU_PUBLIC_REPOSITORY_PATH }}
          ENV_FILE_PATH: ./.env
