name: 同步 python 公共仓库

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: 检出代码
        uses: actions/checkout@v2

      - name: 克隆公共仓库
        run: git clone https://github.com/WYN-GraduationProject/WYN-GraduationProject-common.git

      - name: 复制文件
        run: |
          cd WYN-GraduationProject-common
          git checkout main
          source .env
          cp -a -r -f ./proto/ ${PUBLIC_REPOSITORY_PATH}/proto/
          cp -a -r -f ./python_common/utils/ ${PUBLIC_REPOSITORY_PATH}/python_common/
          cp -a -r -f ./python_common/proto/ ${PUBLIC_REPOSITORY_PATH}/python_common/
          cp -a -r -f ./proto_build/python/proto ${PUBLIC_REPOSITORY_PATH}/python_common/
          cp -a -r -f ./docker-compose.yml ${PUBLIC_REPOSITORY_PATH}/
          cp -a -r -f .env ${PUBLIC_REPOSITORY_PATH}/
        env:
          _321CQU_PUBLIC_REPOSITORY_PATH: ${{ secrets.PUBLIC_REPOSITORY_PATH }}
          ENV_FILE_PATH: ./.env
